name: GitLeaks Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitLeaks
      run: |
        curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.16.4/gitleaks_8.16.4_linux_x64.tar.gz | tar -xvz -C /tmp
        sudo mv /tmp/gitleaks /usr/local/bin/gitleaks

    - name: Run GitLeaks scan
      run: |
        gitleaks detect --source . --config twilio-gitleaks.toml

    - name: Upload GitLeaks report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gitleaks-report
        path: gitleaks-report.json
